ALTER TABLE formulacoes
    ADD COLUMN umidade DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ADD COLUMN peso_bloco_kg DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ADD COLUMN total_blocos BIGINT DEFAULT 0 NOT NULL;

